pipeline {
    agent any
	node ("${Var_NodeName}") 
	{
		echo "NODE_NAME: ${NODE_NAME}"
	}

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
